logging:
  level:
    root: INFO

server:
  port: 8097

services:
  # if need to go to another services

kafka:
  bootstrapAddress: localhost:9092
  # topic:
  groupId: transportation-api-gateway
  syncCacheTopic: sync-cache-encrypted

  properties:
    security:
      protocol: PLAINTEXT
    ssl:
      key-password: null
      key-store-location: /etc/config/ssl/mq.jks
      key-store-password: null
      key-store-type: JKS
      trust-store-location: /etc/config/ssl/mq.jks
      trust-store-password: null
      trust-store-type: JKS