version: "3"
services:
  postgres:
    image: 'postgres:12.4-alpine'
    platform: linux/amd64
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 123
  s3mock:
    image: 'adobe/s3mock'
    platform: linux/amd64
    container_name: 's3mock'
    ports:
      - '9090:9090'
      - '9191:9191'
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    platform: linux/amd64
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    platform: linux/amd64
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  fake-smtp-server:
    image: 'reachfive/fake-smtp-server'
    platform: linux/amd64
    container_name: fake-smtp-server
    ports:
      - '1080:1080'
      - '1025:1025'
  sonarqube:
    image: 'sonarqube:latest'
    platform: linux/amd64
    container_name: sonarqube
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: 'true'
    ports:
      - '9000:9000'